//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Bullet 
{
	private int damage = 50;
	public int Damage
	{
		get
		{
			return damage;
		}
		set
		{
			damage = value;
		}

	}
		
}

